### PR TITLE
ECI-877: Fix Social Course compatibility with Open Social groups behaviour

### PR DESCRIPTION
**Pull request by denysyukm**

### CODE REVIEW

**Comment by Kingdutch** [comment]
Hey @denysyukm and @ribel,

Can you provide some explanation on why this is done? I understand that we have some code duplication. However, implementing this hook will opt courses into quite a bit more functionality for groups than just the code that we're removing. 

We currently use this hook to signal to Open Social what it should use for it's groups. However, a course is not an Open Social group (it has very different content, usage and access restrictions).

I think in this case the code duplication is good because it ensures that Open Social groups can change without breaking courses and we should not implement this hook.

**Comment by ribel** [comment]
@Kingdutch I see your point and thank you for bringing it to attention.
The main reason for this PR is to make Group VBO work on Courses. And for that we need to implement `hook_social_group_types_alter()` there. The same hook is already implemented for Challenge group type for quite some time and it works well there. 

I think it's better to use this hook rather than have duplication of code because in this way we can use the same flow and future improvements for groups also in courses without copy/paste (as for example with VBO). And for now, this is used only for few things, like submit action after join/leave or cancel action during the creation of course/group which is the same.

**Comment by ribel** [comment]
@denysyukm Please add some description to this PR. See closed PRs as an example.

**Comment by Kingdutch** [comment]
Hi @ribel,

I do understand! I'm worried that in the future some functionality will be implemented for this hook that we don't want for Courses. Perhaps we should look (in the future) into making this more granular so we have "opt-in per group feature" or something.

~ Alexander

**Review by ribel — APPROVED** [review]

**Comment by ribel** [comment]
@robertragas I think it still would be good to merged it as we discussed.

**Pull request merged**
